version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: guia_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - guia_network

volumes:
  postgres_data:

networks:
  guia_network: